version: "3.9"

services:
  rubixml:
    container_name: rubixml
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    volumes:
      - ./:/app
    working_dir: /app
    tty: true
